#!/bin/bash
#
#       /etc/rc.d/init.d/babian
#
# Starts the babian

# chkconfig: 345 96 20
# description: Online analysis front end for babirl
# processname: babian

# Source function library.
. /etc/init.d/functions

RETVAL=0
DIR=/usr/babirl
INSM=/sbin/insmod
RMM=/sbin/rmmod
LSM=/sbin/lsmod

start() {
	${DIR}/babian/babian
}

stop() { 
	killproc babian -2
}

restart() {
        stop
        start
}

reload() {
        restart
}

status_at() {
        echo
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
status)
        status_at
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $?
exit $RETVAL
