#!/bin/bash
#
#       /etc/rc.d/init.d/babimo
#
# Starts the babimo

# chkconfig: 345 96 20
# description: Process service for babirl (not safe process)
# processname: babimo

# Source function library.
. /etc/init.d/functions

RETVAL=0
DIR=/usr/babirl
INSM=/sbin/insmod
RMM=/sbin/rmmod
LSM=/sbin/lsmod

start() {
	${DIR}/babimo/babimo
}

stop() { 
	killproc babimo -2
}

restart() {
        stop
        start
}

reload() {
        restart
}

status_at() {
        echo
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
status)
        status_at
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $?
exit $RETVAL
