/********************************************************************
* TSHistoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSHistoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTSHistoDict();
extern void G__cpp_setup_inheritanceTSHistoDict();
extern void G__cpp_setup_typetableTSHistoDict();
extern void G__cpp_setup_memvarTSHistoDict();
extern void G__cpp_setup_globalTSHistoDict();
extern void G__cpp_setup_memfuncTSHistoDict();
extern void G__cpp_setup_funcTSHistoDict();
extern void G__set_cpp_environmentTSHistoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSHistoDictLN_TClass;
extern G__linked_taginfo G__TSHistoDictLN_TBuffer;
extern G__linked_taginfo G__TSHistoDictLN_TMemberInspector;
extern G__linked_taginfo G__TSHistoDictLN_TObject;
extern G__linked_taginfo G__TSHistoDictLN_string;
extern G__linked_taginfo G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSHistoDictLN_TQObject;
extern G__linked_taginfo G__TSHistoDictLN_TGObject;
extern G__linked_taginfo G__TSHistoDictLN_TGWindow;
extern G__linked_taginfo G__TSHistoDictLN_TGFrame;
extern G__linked_taginfo G__TSHistoDictLN_TGCompositeFrame;
extern G__linked_taginfo G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TSHistoDictLN_TGTextButton;
extern G__linked_taginfo G__TSHistoDictLN_TGMainFrame;
extern G__linked_taginfo G__TSHistoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSHistoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSHistoDictLN_TH1F;
extern G__linked_taginfo G__TSHistoDictLN_TCanvas;
extern G__linked_taginfo G__TSHistoDictLN_FInfo;
extern G__linked_taginfo G__TSHistoDictLN_TSFrame;

/* STUB derived class for protected member access */
