//
// File generated by rootcint at Tue Dec  7 14:20:02 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TSHistoDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TSFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TSFrame(void *p);
   static void deleteArray_TSFrame(void *p);
   static void destruct_TSFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TSFrame*)
   {
      ::TSFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TSFrame", ::TSFrame::Class_Version(), "TSFrame.h", 46,
                  typeid(::TSFrame), DefineBehavior(ptr, ptr),
                  &::TSFrame::Dictionary, isa_proxy, 0,
                  sizeof(::TSFrame) );
      instance.SetDelete(&delete_TSFrame);
      instance.SetDeleteArray(&deleteArray_TSFrame);
      instance.SetDestructor(&destruct_TSFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TSFrame*)
   {
      return GenerateInitInstanceLocal((::TSFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TSFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TSFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TSFrame::Class_Name()
{
   return "TSFrame";
}

//______________________________________________________________________________
const char *TSFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TSFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TSFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TSFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TSFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TSFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TSFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TSFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TSFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class TSFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void TSFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TSFrame.
      TClass *R__cl = ::TSFrame::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*exit", &exit);
      R__insp.Inspect(R__cl, R__parent, "*run", &run);
      R__insp.Inspect(R__cl, R__parent, "*draw", &draw);
      R__insp.Inspect(R__cl, R__parent, "min", &min);
      R__insp.Inspect(R__cl, R__parent, "max", &max);
      R__insp.Inspect(R__cl, R__parent, "evtmax", &evtmax);
      R__insp.Inspect(R__cl, R__parent, "*canvas", &canvas);
      R__insp.Inspect(R__cl, R__parent, "fInfo[10]", fInfo);
      R__insp.Inspect(R__cl, R__parent, "*ht[10]", &ht);
      R__insp.Inspect(R__cl, R__parent, "htn", &htn);
      R__insp.Inspect(R__cl, R__parent, "*fd[10]", &fd);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TSFrame(void *p) {
      delete ((::TSFrame*)p);
   }
   static void deleteArray_TSFrame(void *p) {
      delete [] ((::TSFrame*)p);
   }
   static void destruct_TSFrame(void *p) {
      typedef ::TSFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TSFrame

/********************************************************
* TSHistoDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTSHistoDict();

extern "C" void G__set_cpp_environmentTSHistoDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TSFrame.h");
  G__cpp_reset_tagtableTSHistoDict();
}
#include <new>
extern "C" int G__cpp_dllrevTSHistoDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TSFrame */
static int G__TSHistoDict_327_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TSFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) TSFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->setAction();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->setMinMax((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->setFInfo((int) G__int(libp->para[0]), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->createTH1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->runAnalysis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->drawTH1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->quitFrame();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TSFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TSFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TSFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TSHistoDict_327_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TSFrame G__TTSFrame;
static int G__TSHistoDict_327_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TSFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TSFrame*) (soff+(sizeof(TSFrame)*i)))->~G__TTSFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TSFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TSFrame*) (soff))->~G__TTSFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TSFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTSHistoDict {
 public:
  G__Sizep2memfuncTSHistoDict(): p(&G__Sizep2memfuncTSHistoDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTSHistoDict::*p)();
};

size_t G__get_sizep2memfuncTSHistoDict()
{
  G__Sizep2memfuncTSHistoDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTSHistoDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame))) {
     TSFrame *G__Lderived;
     G__Lderived=(TSFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),G__get_linked_tagnum(&G__TSHistoDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTSHistoDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TSHistoDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TSHistoDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TSFrame */
static void G__setup_memvarTSFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame));
   { TSFrame *p; p=(TSFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TGTextButton),-1,-1,4,"exit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TGTextButton),-1,-1,4,"run=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TGTextButton),-1,-1,4,"draw=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"min=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"max=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"evtmax=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TCanvas),-1,-1,4,"canvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_FInfo),-1,-1,4,"fInfo[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TH1F),-1,-1,4,"ht[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"htn=",0,(char*)NULL);
   G__memvar_setup((void*)0,69,0,0,-1,-1,-1,4,"fd[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TSHistoDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTSHistoDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTSFrame(void) {
   /* TSFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame));
   G__memfunc_setup("TSFrame",658,G__TSHistoDict_327_0_1, 105, G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setAction",938,G__TSHistoDict_327_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMinMax",918,G__TSHistoDict_327_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - min i - - 0 - max "
"i - - 0 - evtmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFInfo",798,G__TSHistoDict_327_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - n u 'string' - 0 - s", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("createTH1",833,G__TSHistoDict_327_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("runAnalysis",1177,G__TSHistoDict_327_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("drawTH1",635,G__TSHistoDict_327_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("quitFrame",942,G__TSHistoDict_327_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TSHistoDict_327_0_9, 85, G__get_linked_tagnum(&G__TSHistoDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TSFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TSHistoDict_327_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TSHistoDict_327_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TSFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TSHistoDict_327_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TSFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TSHistoDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TSHistoDict_327_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TSHistoDict_327_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TSHistoDict_327_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TSHistoDict_327_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TSHistoDict_327_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TSFrame", 784, G__TSHistoDict_327_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTSHistoDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTSHistoDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTSHistoDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TSHistoDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_FInfo = { "FInfo" , 99 , -1 };
G__linked_taginfo G__TSHistoDictLN_TSFrame = { "TSFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTSHistoDict() {
  G__TSHistoDictLN_TClass.tagnum = -1 ;
  G__TSHistoDictLN_TBuffer.tagnum = -1 ;
  G__TSHistoDictLN_TMemberInspector.tagnum = -1 ;
  G__TSHistoDictLN_TObject.tagnum = -1 ;
  G__TSHistoDictLN_string.tagnum = -1 ;
  G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TSHistoDictLN_TQObject.tagnum = -1 ;
  G__TSHistoDictLN_TGObject.tagnum = -1 ;
  G__TSHistoDictLN_TGWindow.tagnum = -1 ;
  G__TSHistoDictLN_TGFrame.tagnum = -1 ;
  G__TSHistoDictLN_TGCompositeFrame.tagnum = -1 ;
  G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TSHistoDictLN_TGTextButton.tagnum = -1 ;
  G__TSHistoDictLN_TGMainFrame.tagnum = -1 ;
  G__TSHistoDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TSHistoDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TSHistoDictLN_TH1F.tagnum = -1 ;
  G__TSHistoDictLN_TCanvas.tagnum = -1 ;
  G__TSHistoDictLN_FInfo.tagnum = -1 ;
  G__TSHistoDictLN_TSFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTSHistoDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_string);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__TSHistoDictLN_FInfo);
   G__tagtable_setup(G__get_linked_tagnum(&G__TSHistoDictLN_TSFrame),sizeof(TSFrame),-1,62464,(char*)NULL,G__setup_memvarTSFrame,G__setup_memfuncTSFrame);
}
extern "C" void G__cpp_setupTSHistoDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTSHistoDict()");
  G__set_cpp_environmentTSHistoDict();
  G__cpp_setup_tagtableTSHistoDict();

  G__cpp_setup_inheritanceTSHistoDict();

  G__cpp_setup_typetableTSHistoDict();

  G__cpp_setup_memvarTSHistoDict();

  G__cpp_setup_memfuncTSHistoDict();
  G__cpp_setup_globalTSHistoDict();
  G__cpp_setup_funcTSHistoDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTSHistoDict();
  return;
}
class G__cpp_setup_initTSHistoDict {
  public:
    G__cpp_setup_initTSHistoDict() { G__add_setup_func("TSHistoDict",(G__incsetup)(&G__cpp_setupTSHistoDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTSHistoDict() { G__remove_setup_func("TSHistoDict"); }
};
G__cpp_setup_initTSHistoDict G__cpp_setup_initializerTSHistoDict;

