extern void cc77_init_register(int irq,int ior,int pbor);
extern int cc77_check_done(int try);
extern int cc77_check_emp_fifo(extern void);
extern int cc77_check_full_fifo(extern void);
extern int cc77_check_lam(extern void);
extern void cc77_read_lam(int *data);
extern void cc77_control(int cnaf);
extern void cc77_read16(int cnaf,short *data);
extern void cc77_read24(int cnaf,short *data);
extern void cc77_write16(int cnaf,short *data);
extern void cc77_write24(int cnaf,int *data);
extern int cc77_block_read16(int mode,int cnaf,short *data,int count);
extern int cc77_block_read24(int mode,int cnaf,unsigned int *data,int count);
extern int cc77_dma_block_read16(int mode,int cnaf,int count);
extern int cc77_dma_block_read24(int mode,int cnaf,int count);
extern void cc77_crate_reset(extern void);
extern void cc77_rfs_enable_interrupt(extern void);
extern void cc77_rfs_disable_interrupt(extern void);
extern void cc77_pci_enable_interrupt(extern void);
extern void cc77_pci_clear_interrupt(extern void);
extern void cc77_crate_enable_lam(int lammask);
extern void cc77_crate_disable_lam(extern void);
extern void cc77_crate_z(int c);
extern void cc77_crate_c(int c);
extern void cc77_crate_seti(int c);
extern void cc77_crate_deli(int c);
extern void cc77_get_csrdata(int *ret);
extern void cc77_get_bmcsdata(int *ret);
