#define init_register          cc77_init_register          
#define check_done             cc77_check_done             
#define check_emp_fifo         cc77_check_emp_fifo         
#define check_full_fifo        cc77_check_full_fifo        
#define check_lam              cc77_check_lam              
#define read_lam               cc77_read_lam               
#define control                cc77_control                
#define read16                 cc77_read16                 
#define read24                 cc77_read24                 
#define write16                cc77_write16                
#define write24                cc77_write24                
#define block_read16           cc77_block_read16           
#define block_read24           cc77_block_read24           
#define dma_block_read16       cc77_dma_block_read16       
#define dma_block_read24       cc77_dma_block_read24       
#define crate_reset            cc77_crate_reset            
#define rfs_enable_interrupt   cc77_rfs_enable_interrupt   
#define rfs_disable_interrupt  cc77_rfs_disable_interrupt  
#define pci_enable_interrupt   cc77_pci_enable_interrupt   
#define pci_clear_interrupt    cc77_pci_clear_interrupt    
#define crate_enable_lam       cc77_crate_enable_lam       
#define crate_disable_lam      cc77_crate_disable_lam      
#define crate_define_lam       cc77_crate_define_lam
#define crate_z                cc77_crate_z                
#define crate_c                cc77_crate_c                
#define crate_seti             cc77_crate_seti             
#define crate_deli             cc77_crate_deli             
#define get_csrdata            cc77_get_csrdata            
#define get_bmcsdata           cc77_get_bmcsdata
#ifdef CAMACINT
#define get_irq                cc77_get_irq
#endif
